name: hms
description: A new Flutter application.


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_splash_screen: ^1.1.0
  carousel_slider: ^0.0.4
  firebase_core:
  firebase_auth:
  cloud_firestore:
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.6
  firebase_database: ^6.1.2
  provider: ^5.0.0
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_launcher_icons:
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/launchericon.png"


flutter:


  uses-material-design: true
  assets:
    - assets/

